meilisearch/mini-dashboard

- src/components/Results/Hit.js
The `isObject` function is slowing down the page rendering, so I decided to simplify it by removing the parsing step and replaced it with a simple check of the first and last character, not correct but much faster. MeiliSearch will probably never return invalid JSON objects anyway 😄
There also is the `emotion/css` module that slows down the page rendering.
I also learned that a `yarn build` is much faster as it generates an optimized build 🎉
```bash
yarn build
cd build
python3 -m http.server 8000
```
It could be great if you could make the `yarn build` command to be able to run with the server running on `127.0.0.1:7700` and add these three commands in the readme, it would help others run the server in production and avoid performances issues. 😄
> Speed up the isObject function

- src/components/Input.js
The attribute `type` does not spread into the final HTML input element in the component `Input`
- Add type attribute to the `InputField` in the component `Input` 
:tada:
> Add type attribute to component Input

- .github/workflows/release-drafter.yml
This PR makes use the [meili-bot](https://github.com/meili-bot) credentials.
This will prevent from some failures. Why?
The release drafter is GitHub automation. So the author of the release is an automation.
Your [release push](https://github.com/meilisearch/mini-dashboard/blob/main/.github/workflows/publish-build.yml) is a GitHub automation.
And a GitHub automation cannot trigger another GitHub automation.
It means you cannot trigger your CI push by creating a release where the author is an automation. That's why we use the meili-bot credentials, so that a GitHub user creates the release draft. So the creator of the release is meili-bot and not an automation.
Sorry, not obvious, but we already had troubles with this 😅
> Use RELEASE_DRAFTER_TOKEN secret var

- src/components/Select.js
This PR:
- Removes conditional render for `Menu` in the `Select` component (duplicate because already handled by Reakit)
- Add `type="button"` to the buttons `MenuItem` in the component `Select`
closes #97
> Update Select component

- .github/workflows/tests.yml
- cypress/integration/test-interface.js
- cypress/integration/test-no-api-key-required.js
- cypress/integration/test-search.js
- cypress/integration/test-select-indexes.js
- package.json
Most of the CI's tests where running on a Docker with an API key beeing required. 
In order to speed up the tests, some of them where moved to the Docker not needing an API key.
> Run most tests without needing an api key

- src/components/Header/HelpCenter.js
After replacing the old logo by the new one, one card inside the help center (the one with the new logo) doesn't have the same height as the others. This PR fixes it, as it isn't very esthetic.
> Fix help center cards height

- .github/workflows/tests.yml
CI was failing after the upgrade to node 16:
This PR fixes it
> Fix CI cypress fail after upgrade to node 16

- cypress/e2e/test-api-key-required.cy.js
- src/components/ApiKeyModalContent.js
Fixes #280
- This PR have solved the issue of key enter on API KEY modal
On key enter, field will be validate
> Accessibility: make pressing the enter key, validate the admin key modal #280

- README.md
While this is the prefered way I would want to achieve (see [this issue](https://github.com/meilisearch/integration-automations/issues/122)), the pre-release script only works when the versions are provided with the patch version.
Until this process is changed in the scripts, it is better to keep the compatibility line consistent with the other SDK's
> Fix compatibility with Meilisearch line in README for consistency

- src/components/Results/Hit.js
fixes: #377 
The crash was due to the way `instantsearch` transforms fields when they are highlighted. For example, given this document:
```js
{
id: 1,
foo: { some_property: "abc", value: { value: "plouf"}  },
otherObject: { some_property: "abc", paf: 1  },
url: "https://x.com/img.png",
test: [1, 2, 3]
}
```
When returned by instantsearch, they are transformed the following way:
```js
{
id: 1,
foo: { some_property: "abc", value: { value: "plouf"}  },
otherObject: { some_property: "abc", paf: 1  },
url: "https://raw.githubusercontent.com/meilisearch/integration-guides/main/assets/logos/meilisearch_js.svg",
test: [1, 2, 3],
_formatted: {
id: { value: '1'}, // nested in value
foo: { some_property: "abc", value: { value: "plouf"}  }, // not changed
otherObject: { some_property: "abc", paf: 1 …
```
> Fix crash when nesting field contains value key

- .github/dependabot.yml
Styling, testing, and other none production-related dependencies are ignored in this PR. This avoids unnecessary maintenance on low-importance tasks.
> Ignore dev dependencies in dependabot updates

- src/components/OnBoarding.js
The current link (`https://www.meilisearch.com/docs/reference/features/authentication#master-key`) gives a 404. This PR updates it to the master and API keys guide.
> Update "Set your API key (optional)" link

- src/App.js
- src/components/Header/index.js
- src/components/SearchBox.js
This PR adds a behavior where if you make a search request (you write something in the searchbar), the `getIndexes` method is re-triggered. Updating the stats of the index and showcasing its documents without having to reload the page.
fixes: #300
> Retrigger getIndexes on empty index search

- public/index.html
Fixes #448 
Adds a `noindex` metatag to prevent search engines from indexing the deployed mini-dashboards.
> Add noindex metatag to prevent search engines from indexing the mini-dashboard

- .eslintrc.json
- src/App.js
- src/components/CloudBanner.js
- src/components/Link.js
- src/components/Typography.js
Fixes: #441 
A banner now automatically appears at the top of the page with a call to action to the Meilisearch cloud.
To deactivate the banner, you can add `cloud_banner=false` to the query parameters.
> Add a call to action banner for the cloud

- src/components/Results/Hit.js
- src/components/Results/index.js
It can happen that a document contains no fields if none of these fields are present in the displayedAttributes setting. For example, if I have a document with an id field, but in my displayedAttributes setting I did not include `id`, the hits I receive from a search are empty
```
{
hits : [ {} ]
}
```
In this particular case, the mini-dashboard would crash.
In this PR I added a safeguard where if there are no field, a document still appears but empty
I also added a warning in their console just in case they want to understand what is happening
> Fix bug where interface crashes if hit has no field

- src/components/Results/Hit.js
Disable eslint on a line using a warning to inform user that their document are empty.
> Disable eslint error on a console warning

- cypress/e2e/test-interface.cy.js
- cypress/e2e/test-select-indexes.cy.js
- package.json
- src/components/Results/InfiniteHits.js
- src/components/Select.js
- yarn.lock
Fixes #167 
- This PR fixes the issue where if you load a lot of datasets ( > 1000 ) the dropdown starts to lag and UX becomes super laggy.
Here's the before and after -
**before**
https://github.com/meilisearch/mini-dashboard/assets/39329182/e72f45d7-f143-460e-afe3-e3858e03fc9d
**after**
https://github.com/meilisearch/mini-dashboard/assets/39329182/bc7f94fb-764c-4a9f-b306-6a6890e2e1a2
> added new dropdown for rendering large list

- src/components/CloudBanner.js
Updates the link in the cloud banner now pointing to the new cloud landing page instead of the pricing page.
> Update link to the cloud page

- .github/dependabot.yml
To avoid being spammed with package updates, we changed from a ignore list to an allow list in a monthly interval.
> Update dependabot.yml from ignore list to allow list

- cypress/e2e/test-api-key-query-param.cy.js
- cypress/e2e/test-interface.cy.js
- cypress/e2e/test-select-indexes.cy.js
- src/App.js
- src/components/Body.js
- src/components/BodyWrapper.js
- src/components/Header/index.js
- src/components/NoMeilisearchRunning.js
- src/context/MeilisearchClientContext.js
- src/index.js
- src/utils/getIndexesListWithStats.js
- src/utils/hasAnApiKeySet.js
- src/utils/shouldDisplayApiKeyModal.js
- src/utils/shouldDisplayCloudBanner.js
- Creation of a `MeilisearchClientContext` for maintainability (instead of passing down 2 clients to the components)
- Functions have been put in specific files (instead of inside the `useEffect`)
- Functions needing to stay in the `App` file are now wrapped inside a `useCallback`
- Some components have been put in specific files (instead of inside the `App` file)
- Fix the amount of search requests made on page load (from 20 down to 4)
- The Header now doesn't show up when Meilisearch isn't running (this caused re-rendering and search requests)
- Fix tests (addition of waiting_time as a quick fix, as Cypress is now too fast and CI was failing). Tests would need a refacto anyway 🤷 
Thank you so much for contributing to …
> fix: search request amount made on page arrival

- package.json
- yarn.lock
Revert the bump of styled-components from 5.3.9 to 6.1.11
After upgrading the package, some styles are broken, we need to investigate why.
Style after the upgrade:
Style before the upgrade:
> revert: Bump styled-components from 5.3.9 to 6.1.11

- package.json
- yarn.lock
The `minimatch` package has a vulnerability issue with versions < 3.0.5.
This package is used internally through `recursive-readdir`: 
The problem is that `recursive-readdir` is used by react-script (create-react-app), which is not maintained anymore.
To fix this issue, the `package.json` has been updated with the [resolutions field](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to update `minimatch` to the v3.0.5 (fixing the vulnerability) for the package using the vulnerable version (`recursive-readdir`)  
This should help fixing the vulnerability issue.
> fix(security): minimatch ReDoS vulnerability

- package.json
- yarn.lock
Force the usage of the patched versions of `semver` and `postcss`, both used by `react-scripts` which isn't maintained anymore.
This should fix the "moderate" security issues of this repository
> fix(security): react-scripts packages vulnerabilities

- src/components/Body.js
Fixes #589
Save the state of the panel (open / closed) in the localstorage, so that when the users close it and refresh, it doesn't show up again.
https://github.com/user-attachments/assets/aae29c2e-cb00-40cf-b3fd-d32d97bfd20c
> feat(rightPanel): store the state of the panel in the localStorage

- .github/workflows/tests.yml
As we want to move away from bors and use merge queues, we need tests to be triggered when PRs are added to the merge queue.
As this wasn't implemented, we can see that PRs pushed the merge queue failed to merge because the tests weren't trigger, e.g. #609
- Implements `merge_group` trigger as explained in the [merge queue docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions)
> Trigger `tests` workflow on merge queue

- src/hooks/useExportDataset.js
Fix a bug where the export route wasn't called with the API key.
> Use the api key when calling the export route
