- package.json
- yarn.lock
> Remove lint-staged

- src/App.js
- src/components/ApiKeyModalContent.js
> Fixes relatives to the upgrade of instant meilisearch v0.5.0

- .eslintrc.json
- .github/workflows/tests.yml
- .gitignore
- bors.toml
- cypress.json
- cypress/integration/test-api-key.js
- cypress/integration/test-no-meilisearch.js
- package.json
- yarn.lock
Closes #56 
Setup of Cypress and addition of a few tests : 
- Test the view if MeiliSearch isn't running
- Test the API key with a running MeiliSearch
More tests to come in other PRs ! 
Also : edition of the CI to run the Cypress tests
To run the tests with no MeiliSearch running : 
`yarn cy:run:test-no-meilisearch`
To run the tests with a MeiliSearch running (make sure to provide `masterKey` as an api key): 
`yarn cy:run`
⚠️ Make sure to test with the v0.21.0 of MeiliSearch (otherwise, the `Should ask for an API key` test will fail !)
> Add Cypress

- src/components/Results/Hit.js
Closes #93
URL's highlight doesn't appear, making it difficult to visualize why some elements are returned from the search.
Addition of the Highlight component inside the Link component. 
Before: 
After:
> Fix highlight inside links

- src/App.js
- src/components/Header/index.js
> Add MeiliSearch version

- src/components/Results/Hit.js
Fixes #126.
It's a pragmatic solution for the issue, it doesn't try a perfect validation as we're not editing here anyway.
> Make link check for fields more strict

- CONTRIBUTING.md
Add Hacktoberfest section to CONTRIBUTING.md
> Add Hacktoberfest section to CONTRIBUTING.md

- cypress/integration/test-api-key.js
- src/App.js
- src/components/Header/index.js
> Fix modal focus

- .github/workflows/tests.yml
- .gitignore
> Add dependency cache for ci

- cypress.json
- cypress/integration/test-api-key-required.js
- src/App.js
- src/components/Header/index.js
- src/components/Modal.js
> Add tests for api key button

- .github/workflows/tests.yml
- bors.toml
- cypress/integration/test-api-key-required.js
- cypress/integration/test-no-api-key-required.js
- package.json
> Add tests if no api key is required

- .github/workflows/tests.yml
- cypress/integration/test-api-key-required.js
- package.json
- src/App.js
- yarn.lock
> Update for version v0.24.0rc2

- cypress/fixtures/pokemon.json
- cypress/integration/test-interface.js
- cypress/integration/test-select-indexes.js
- src/components/Header/HelpCenter.js
> Test interface

- package.json
Upgrade Meilisearch and Instant MeiliSearch to their latest beta. See their repo and changelog for more information
> Update to version 0.1.7

- cypress/integration/test-api-key-required.js
- cypress/integration/test-no-api-key-required.js
- src/App.js
- src/components/ApiKeyModalContent.js
- src/components/Header/index.js
> Replace private api key mention

- package.json
> Update browserslist in package.json

- cypress/support/commands.js
- src/App.js
- src/components/ApiKeyModalContent.js
> Replace MeiliSearch wording with Meilisearch

- .github/ISSUE_TEMPLATE/config.yml
Add a link to the main repo of Meilisearch in the github issue template
> Add link to meilisearch's main repo in the issue template

- LICENCE
> Update copyright in licence file

- src/version/client-agents.js
It should be `v0.2.0` not `v.0.2.0` :)
> Remove dot prefix in the version

- src/components/Results/InfiniteHits.js
Fixes #303
The problem was that we were trying to guess if the current field is an image with a regex only. 
This is not good enough, as some images don't have any extension but are still images (example: [this image](https://images.unsplash.com/photo-1552566626-52f8b828add9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTg4Mzh8MHwxfHJhbmRvbXx8fHx8fHx8fDE2NTA0NDgxMDQ&ixlib=rb-1.2.1&q=80&w=400&utm_source=restaurants_demo&utm_medium=referral&utm_campaign=api-credit))
To fix this, I added an other test that creates a new Image object and tries to load the URL that is provided. This may not be the best way to fix this, but I didn't find a better one 🤷‍♀️
> Fix image display

- CONTRIBUTING.md
- README.md
> Remove npm mentions inside readme and contributing

- cypress/e2e/test-api-key-required.cy.js
test-api-key-required.cy.js file
Fixes #334
- Add cy.deleteAllIndexes() in before block in the test file test-api-key-required.cy.js
> Add cy.deleteAllIndexes() in before block in test-api-key-required.cy.js

- .github/workflows/tests.yml
- Update Meilisearch's version in CI
> Update meilisearch version in ci

- src/components/Results/InfiniteHits.js
Fixes #379
Update the way the values of the documents are tested as images, to only make the tests on links.
> Fix calls on each document's value

- CONTRIBUTING.md
This PR's add the process on how to add the mini-dashboard to the Meilisearch engine.
> Add process on adding the mini dashboard into meilisearch

- README.md
We want to let users suggest features and let contributors implement them.
Additionally, I added a better explanation on what the mini dashboard is.
> Update the readme with changes on the issues policy

- .eslintrc.json
- src/App.js
- src/components/ApiKeyAwarenessBanner.js
- src/components/Header/index.js
- src/components/Typography.js
- src/components/icons/AlertCircle.js
- src/components/icons/index.js
- src/components/icons/svg/alert-circle.svg
Fixes #434 
Took creation reference from  #442
- Shows api_key (warning) banner. If the api_key is found in the url.
> Added api-key warning banner

- cypress/e2e/test-interface.cy.js
- cypress/e2e/test-select-indexes.cy.js
- package.json
- src/components/Results/InfiniteHits.js
- src/components/Select.js
- yarn.lock
Fixes: #463 
Until we fix the issue, reverting these changes.
@vaibhav135
> Revert changes introducing a better way to render large index lists

- README.md
- cypress/e2e/test-interface.cy.js
- src/components/Header/HelpCenter.js
- Updates all links from `https://discord.gg/meilisearch` to `https://discord.meilisearch.gg`
> Update discord links

- package.json
- src/version/version.js
Update version to v0.2.12 to prepare for a release ([see the changes](https://github.com/meilisearch/mini-dashboard/releases))
> Update version with v0.2.12

- cypress.config.js
Update the Cypress config:
- Add `retries: 2` to handle flaky tests
- Add `watchForFileChanges: true` for development testing
> chore: update cypress config

- .github/workflows/publish-build.yml
- .github/workflows/tests.yml
- package.json
- yarn.lock
Upgrade node version to v18 in the CI.
This is required to upgrade packages to their latest version (and potentially fix vulnerability issues)
It also upgrades Cypress to its latest, as it is required to work along with its latest GitHub action
> ci: upgrade node to version 18

- .storybook/main.js
- .storybook/preview.js
- package.json
- yarn.lock
Upgrade Storybook to the latest version (v8).
This might fix security issues we have in the repository.
> build(deps): bump storybook version to v8

- .github/dependabot.yml
Update dependabot file to allow any dependencies.
This would help fix potential vulnerability issues that could come later.
> Update dependabot file

- Dockerfile
- README.md
N/A
- Adds a sample Dockerfile
- Adds instructions on how to build and run the mini dashboard using docker
> Provide a sample Dockerfile and instructions to build & run it

- src/components/Header/index.js
- src/components/Results/Hit.js
- src/components/Typography.js
Fixes #494
Removes allcaps from keys
- [ X] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ X] Have you read the contributing guidelines?
- [ X] Have you made sure that the title is accurate and descriptive of the changes?
> unset textTransform when displaying keys

- package.json
- src/utils/hasAnApiKeySet.js
- yarn.lock
> Bump meilisearch from 0.38.0 to 0.44.1

- package.json
- yarn.lock
- bump `meilisearch` to 0.48.2
- bump `@meilisearch/instant-meilisearch` to 0.24
> Bump `meilisearch` and `@meilisearch/instant-meilisearch`

- cypress/e2e/test-select-indexes.cy.js
- Make the test intent of the test clearer
- Remove unnecessary changes from #580 
> Clean up `test select index` test case

- package.json
Required to [publish the new build](https://github.com/meilisearch/mini-dashboard/actions/runs/13520425778)
> Bump to 0.2.17

- package.json
- yarn.lock
Fixes #600
Fix the vulnerabilities that were introduced by some packages
> fix(SOC2): fix vulnerabilities (nth-check / postcss / esbuild)

- package.json
- src/version/version.js
Update the version to prepare for the release
> Update version for the next release (v0.2.20)

- src/components/Results/Hit.js
Fixes #632
Fixes https://linear.app/meilisearch/issue/ENGPROD-10/mini-dashboard-crashes
Fixes https://linear.app/meilisearch/issue/EXP-98/mini-dashboard-crashes
- Fix crash on null values in Hit component
> fix: crash on null values in Hit component
